name: Build Overbrowsing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 7 * * 1'

permissions: write-all
jobs:
  optimize_images_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conditional workflow steps
        run: |
          yarn install
          yarn build

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

          # Check if gh-pages branch exists
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout -b gh-pages
          fi

          # Handle local modifications
          git add -u
          git reset --hard

          git merge main

          # Delete all the files on the branch that aren't being served statically.
          git ls-files | grep -v '^_site/' | xargs rm -r

          # Move all contents of _site to the root
          mv _site/* .

          # Delete the _site folder
          rm -r _site

          git add .
          git commit -m "Workflow Run: Generate Compressed Images"
          git push -u -f origin gh-pages
